export const CHOICES_EVENT_TYPES = [
	{ id: '911TelephoneOutage', label: '911 Telephone Outage' },
	{ id: 'AdministrativeMessage', label: 'Administrative Message' },
	{ id: 'AirQualityAlert', label: 'Air Quality Alert' },
	{ id: 'AirStagnationAdvisory', label: 'Air Stagnation Advisory' },
	{ id: 'AshfallAdvisory', label: 'Ashfall Advisory' },
	{ id: 'AshfallWarning', label: 'Ashfall Warning' },
	{ id: 'AvalancheAdvisory', label: 'Avalanche Advisory' },
	{ id: 'AvalancheWarning', label: 'Avalanche Warning' },
	{ id: 'AvalancheWatch', label: 'Avalanche Watch' },
	{ id: 'BeachHazardsStatement', label: 'Beach Hazards Statement' },
	{ id: 'BlizzardWarning', label: 'Blizzard Warning' },
	{ id: 'BlowingDustAdvisory', label: 'Blowing Dust Advisory' },
	{ id: 'BlowingDustWarning', label: 'Blowing Dust Warning' },
	{ id: 'BlueAlert', label: 'Blue Alert' },
	{ id: 'BriskWindAdvisory', label: 'Brisk Wind Advisory' },
	{ id: 'ChildAbductionEmergency', label: 'Child Abduction Emergency' },
	{ id: 'CivilDangerWarning', label: 'Civil Danger Warning' },
	{ id: 'CivilEmergencyMessage', label: 'Civil Emergency Message' },
	{ id: 'CoastalFloodAdvisory', label: 'Coastal Flood Advisory' },
	{ id: 'CoastalFloodStatement', label: 'Coastal Flood Statement' },
	{ id: 'CoastalFloodWarning', label: 'Coastal Flood Warning' },
	{ id: 'CoastalFloodWatch', label: 'Coastal Flood Watch' },
	{ id: 'ColdWeatherAdvisory', label: 'Cold Weather Advisory' },
	{ id: 'DenseFogAdvisory', label: 'Dense Fog Advisory' },
	{ id: 'DenseSmokeAdvisory', label: 'Dense Smoke Advisory' },
	{ id: 'DustAdvisory', label: 'Dust Advisory' },
	{ id: 'DustStormWarning', label: 'Dust Storm Warning' },
	{ id: 'EarthquakeWarning', label: 'Earthquake Warning' },
	{ id: 'EvacuationImmediate', label: 'Evacuation Immediate' },
	{ id: 'ExtremeHeatWarning', label: 'Extreme Heat Warning' },
	{ id: 'ExtremeHeatWatch', label: 'Extreme Heat Watch' },
	{ id: 'ExtremeColdWarning', label: 'Extreme Cold Warning' },
	{ id: 'ExtremeColdWatch', label: 'Extreme Cold Watch' },
	{ id: 'ExtremeFireDanger', label: 'Extreme Fire Danger' },
	{ id: 'ExtremeWindWarning', label: 'Extreme Wind Warning' },
	{ id: 'FireWarning', label: 'Fire Warning' },
	{ id: 'FireWeatherWatch', label: 'Fire Weather Watch' },
	{ id: 'FlashFloodStatement', label: 'Flash Flood Statement' },
	{ id: 'FlashFloodWarning', label: 'Flash Flood Warning' },
	{ id: 'FlashFloodWatch', label: 'Flash Flood Watch' },
	{ id: 'FloodAdvisory', label: 'Flood Advisory' },
	{ id: 'FloodStatement', label: 'Flood Statement' },
	{ id: 'FloodWarning', label: 'Flood Warning' },
	{ id: 'FloodWatch', label: 'Flood Watch' },
	{ id: 'FreezeWarning', label: 'Freeze Warning' },
	{ id: 'FreezeWatch', label: 'Freeze Watch' },
	{ id: 'FreezingFogAdvisory', label: 'Freezing Fog Advisory' },
	{ id: 'FreezingSprayAdvisory', label: 'Freezing Spray Advisory' },
	{ id: 'FrostAdvisory', label: 'Frost Advisory' },
	{ id: 'GaleWarning', label: 'Gale Warning' },
	{ id: 'GaleWatch', label: 'Gale Watch' },
	{ id: 'HazardousMaterialsWarning', label: 'Hazardous Materials Warning' },
	{ id: 'HazardousSeasWarning', label: 'Hazardous Seas Warning' },
	{ id: 'HazardousSeasWatch', label: 'Hazardous Seas Watch' },
	{ id: 'HazardousWeatherOutlook', label: 'Hazardous Weather Outlook' },
	{ id: 'HeatAdvisory', label: 'Heat Advisory' },
	{ id: 'HeavyFreezingSprayWarning', label: 'Heavy Freezing Spray Warning' },
	{ id: 'HeavyFreezingSprayWatch', label: 'Heavy Freezing Spray Watch' },
	{ id: 'HighSurfAdvisory', label: 'High Surf Advisory' },
	{ id: 'HighSurfWarning', label: 'High Surf Warning' },
	{ id: 'HighWindWarning', label: 'High Wind Warning' },
	{ id: 'HighWindWatch', label: 'High Wind Watch' },
	{ id: 'HurricaneForceWindWarning', label: 'Hurricane Force Wind Warning' },
	{ id: 'HurricaneForceWindWatch', label: 'Hurricane Force Wind Watch' },
	{ id: 'HurricaneWarning', label: 'Hurricane Warning' },
	{ id: 'HurricaneWatch', label: 'Hurricane Watch' },
	{ id: 'HydrologicOutlook', label: 'Hydrologic Outlook' },
	{ id: 'IceStormWarning', label: 'Ice Storm Warning' },
	{ id: 'LakeEffectSnowWarning', label: 'Lake Effect Snow Warning' },
	{ id: 'LakeWindAdvisory', label: 'Lake Wind Advisory' },
	{ id: 'LakeshoreFloodAdvisory', label: 'Lakeshore Flood Advisory' },
	{ id: 'LakeshoreFloodStatement', label: 'Lakeshore Flood Statement' },
	{ id: 'LakeshoreFloodWarning', label: 'Lakeshore Flood Warning' },
	{ id: 'LakeshoreFloodWatch', label: 'Lakeshore Flood Watch' },
	{ id: 'LawEnforcementWarning', label: 'Law Enforcement Warning' },
	{ id: 'LocalAreaEmergency', label: 'Local Area Emergency' },
	{ id: 'LowWaterAdvisory', label: 'Low Water Advisory' },
	{ id: 'MarineWeatherStatement', label: 'Marine Weather Statement' },
	{ id: 'NuclearPowerPlantWarning', label: 'Nuclear Power Plant Warning' },
	{ id: 'RadiologicalHazardWarning', label: 'Radiological Hazard Warning' },
	{ id: 'RedFlagWarning', label: 'Red Flag Warning' },
	{ id: 'RipCurrentStatement', label: 'Rip Current Statement' },
	{ id: 'SevereThunderstormWarning', label: 'Severe Thunderstorm Warning' },
	{ id: 'SevereThunderstormWatch', label: 'Severe Thunderstorm Watch' },
	{ id: 'SevereWeatherStatement', label: 'Severe Weather Statement' },
	{ id: 'ShelterInPlaceWarning', label: 'Shelter In Place Warning' },
	{ id: 'ShortTermForecast', label: 'Short Term Forecast' },
	{ id: 'SmallCraftAdvisory', label: 'Small Craft Advisory' },
	{ id: 'SnowSquallWarning', label: 'Snow Squall Warning' },
	{ id: 'SpecialMarineWarning', label: 'Special Marine Warning' },
	{ id: 'SpecialWeatherStatement', label: 'Special Weather Statement' },
	{ id: 'StormSurgeWarning', label: 'Storm Surge Warning' },
	{ id: 'StormSurgeWatch', label: 'Storm Surge Watch' },
	{ id: 'StormWarning', label: 'Storm Warning' },
	{ id: 'StormWatch', label: 'Storm Watch' },
	{ id: 'Test', label: 'Test' },
	{ id: 'TornadoWarning', label: 'Tornado Warning' },
	{ id: 'TornadoWatch', label: 'Tornado Watch' },
	{ id: 'TropicalCycloneLocalStatement', label: 'Tropical Cyclone Local Statement' },
	{ id: 'TropicalStormWarning', label: 'Tropical Storm Warning' },
	{ id: 'TropicalStormWatch', label: 'Tropical Storm Watch' },
	{ id: 'TsunamiAdvisory', label: 'Tsunami Advisory' },
	{ id: 'TsunamiWarning', label: 'Tsunami Warning' },
	{ id: 'TsunamiWatch', label: 'Tsunami Watch' },
	{ id: 'TyphoonWarning', label: 'Typhoon Warning' },
	{ id: 'TyphoonWatch', label: 'Typhoon Watch' },
	{ id: 'VolcanoWarning', label: 'Volcano Warning' },
	{ id: 'WindAdvisory', label: 'Wind Advisory' },
	{ id: 'WinterStormWarning', label: 'Winter Storm Warning' },
	{ id: 'WinterStormWatch', label: 'Winter Storm Watch' },
	{ id: 'WinterWeatherAdvisory', label: 'Winter Weather Advisory' },
]
